config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'homes/items'
    get 'homes/customers'
    get 'homes/cart_items'
    get 'homes/orders'
    get 'homes/addresses'
  end
  devise_for :admin, controllers: {
  sessions:      'admin/sessions',
}

  devise_for :customers, controllers: {
  registrations:      'public/registrations',
  sessions:      'public/sessions',
}
# devise_for :customers, controllers: {
#   sessions:      'customers/sessions',
#   passwords:     'customers/passwords',
#   registrations: 'customers/registrations'
# }
scope module: :public do
  # get "/customers/sign_up" => "registrations#new", as: :new_customer_registration
  # post "/customers" => "registrations#create", as: :customer_registration
  # get "/customers/sign_in" => "sessions#new", as: :new_customer_session
  # post "/customers/sign_in" => "sessions#create", as: :customer_session
  # delete "/customers/sign_out" => "sessions#destroy", as: :destroy_customer_session
  root "homes#top"
  resources :homes, only:[:top]
  get "/about" => "homes#about"
  resources :items, only:[:index, :show]
  get "/customers/exit" => "customers#exit"
  patch "/customers/withdraw" => "customers#withdraw"
  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :customers, only:[:show, :edit, :update]
  resources :cart_items, only:[:index, :update, :create, :destroy]
  get "/orders/complete" => "orders#complete"
  post "/orders/confirm" => "orders#confirm"
  resources :orders, only:[:new, :index, :show, :create]
  resources :addresses, except:[:new, :show]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
namespace :admin do
  get "/" => "homes#top", as: :root
  resources :items
  resources :customers, only:[:index, :show, :edit, :update]
  resources :orders, only:[:show]
  put "/order_details/:id" => "order_details#update"
end

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
     belongs_to :customer
     belongs_to :item
 def subtotal
    item.with_tax_price * amount
 end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :is_deleted, inclusion: { in: [true, false] }
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/item.rb
class Item < ApplicationRecord
 attachment :image
 has_many :cart_items, dependent: :destroy
 has_many :order_details, dependent: :destroy
 has_many :orders, through: :order_details
def with_tax_price
    (price * 1.1).floor
end
end

app/models/order.rb
class Order < ApplicationRecord

enum payment_method: { credit_card: 0, transfer: 1 }
belongs_to :customer
has_many :order_details, dependent: :destroy
has_many :items, through: :order_details
has_one :current_order_order_detail, -> {where(main_flg: true)}, class_name: 'OrderDetail'
has_one :current_item, through: :current_order_order_detail, source: :order_detail
def subtotal
    item.order.with_tax_price * amount
end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
def with_tax_price
    (price * 1.1).floor
end
    
def subtotal
    item.order.with_tax_price * amount
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   layout 'admin'
  def top
   @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
     layout 'admin'
      before_action :authenticate_admin!
    def index
        @items = Item.all
    end

    def new
        @item = Item.new
    end

    def show
        @item = Item.find(params[:id])
    end


    def create
        item = Item.new(item_params)
        item.save
        redirect_to admin_item_path(item.id)
    end

    def edit
        @item = Item.find(params[:id])
    end

    def update
        item = Item.find(params[:id])
        item.update(item_params)
        redirect_to admin_item_path(item.id)
    end

    private

    def item_params
        params.require(:item).permit(:name, :introduction, :price, :image)
    end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    layout 'admin'
     before_action :authenticate_admin!

 def show
     @order = Order.find(params[:id])
     @customer = @order.customer
     @order_details = @order.order_details
     @total = 0
 end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  layout 'admin'
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def current_cart_item
  #   if session[:cart_item_id]
  #     @cart_item = CartItem.find(session[:cart_item_id])
  #   else
  #     @cart_item = CartItem.create
  #     session[:cart_item_id] = @cart_item.id
  #   end
  # end
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/items/edit.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-8 offset-md-2">
<div class ="w-25 p-2 m-3" style ="background-color: #eee;">商品編集</div>


<%= form_with model:@item, url: admin_item_path(@item), method: :patch, local:true do |f| %>
<table>
<tr>
  <th>商品画像</th>
  <td><%= f.attachment_field :image %></td>
</tr>

<tr>
    <th>商品名</th>
    <td><%=f.text_field :name %></td>
</tr>

<tr>
    <th>商品説明</th>
    <td><%=f.text_area :introduction %></td>
</tr>


<tr>
    <th>税抜き価格</th>
    <td><%=f.text_field :price %>円</td>
</tr>

<tr>
    <td></td>
    <td><%= f.submit'変更を保存',class: "btn btn-sm btn-success" %></td>
</tr>
<% end %>
</table>

app/views/admin/items/index.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-8 offset-md-2">
<div class ="w-25 p-2 m-3" style ="background-color: #eee;">商品一覧</div>
<button type="button" class="btn btn-light rounded-circle p-0" style="width:2rem;height:2rem;"><%= link_to "＋",new_admin_item_path %></button>
<table class="table table-hover table-inverse">
    <thead>
        <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜き価格</th>
            <th colspan="3"></th>
        </tr>
    </thead>
        <tbody>
            <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name,admin_item_path(item.id), class: 'widelink' %></td>
            <td><%= item.price %></td>
            <td><%= item.genre_id %></td>
            <td><%= item.is_active %></td>
          </tr>
          <% end %>
        </tbody>
</table>
</div>
</div>
</div>

app/views/admin/items/new.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-8 offset-md-2">
<div class ="w-25 p-2 m-3" style ="background-color: #eee;">商品新規登録</div>

<%= form_with model:@item, url: admin_items_path, method: :post,  local:true do |f| %>
<table>

<tr>
  <th>商品画像</th>
  <td><%= f.attachment_field :image %>
</tr>

<tr>
  <th>商品名</th>
  <td><%= f.text_field :name %></td>
</tr>
<tr>
   <th>商品説明</th>
   <td><%= f.text_area :introduction %></td>
</tr>

<tr>
    <th>税込価格</th>
    <td><%= f.text_field :price %>円</td>
</tr>
<tr>
   <td></td>
   <td><%= f.submit '新規登録',class: "btn btn-sm btn-success" %></td>
</tr>


<% end %>
</table>
</div>
</div>
</div>
</div>

app/views/admin/items/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-10 offset-md-1">
<div class ="w-25 p-2 m-3" style ="background-color: #eee;">商品詳細</div>

<div class="container">
<div class="row">
<div class="col-md-3">
    <%= attachment_image_tag @item, :image, :fill, 200, 200, format: 'jpeg' %>
</div>

<div class="col-md-5">

<table>
<tr>
    <th>商品名</th>
    <td><%= @item.name %></td>
</tr>
<tr>
    <th>商品説明</th>
    <td><%= @item.introduction %></td>
</tr>
<tr>
    <th>税込価格（税抜き価格）</th>
    <td><%= @item.with_tax_price%>円(<%= @item.price %>)円</td>
</tr>
<tr>
    <td></td>
    <td><%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-sm btn-success" %></td>
</tr>


</table>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

app/views/admin/orders/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-8 offset-md-2">
<div class ="w-25 p-2 m-3" style ="background-color: #eee;">注文履歴詳細</div>
<table>
<tr>
    <th>購入者</th>
    <td><%= link_to @order.name, admin_customer_path(@customer.id) %></td>
</tr>

<tr>
    <th>注文日</th>
    <td><%= @order.created_at.strftime('%Y/%m/%d%h%m%s') %></td>
</tr>

<tr>
    <th>配送先</th>
    <td>〒<%= @order.postal_code %></td>
    <td></td>
    <td><%= @order.address %></td>
    <td></td>
    <td><%= @order.name %></td>
</tr>

<tr>
    <th>支払い方法</th>
    <td><%= @order.payment_method_i18n %></td>
</tr>
</table>

<table class="table table-hover table-inverse">
    <thead>
        <tr>
        <th>商品名</th>
        <th>単価（税込）</th>
        <th>数量</th>
        <th>小計</th>
        <th colspan="3"></th>
        </tr>
    </thead>

<tbody>
    <% @order_details.each do |order_detail| %>
  <tr>
    <td><%= order_detail.item.name %></td>
    <td><%= order_detail.item.with_tax_price %></td>
    <th><%= order_detail.amount %></th>
    <% @subtotal =  order_detail.item.with_tax_price * order_detail.amount %>
    <td><%= @subtotal %></td>
    <% @total +=  order_detail.item.with_tax_price * order_detail.amount %>

  　<% end %>

   </tr>

</tbody>
</table>
<table>
    <tr>
    <th>商品合計</th><td><%= @total %></td>
    </tr>
    <tr>
    <th>送料</th><td>800円</td>
    </tr>
    <tr>
    <th>請求合計金額</th><td><%= @order.total_price %></td>
    </tr>
</table>
</div>
</div>
</div>