config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'homes/items'
    get 'homes/customers'
    get 'homes/cart_items'
    get 'homes/orders'
    get 'homes/addresses'
  end
  devise_for :admin, controllers: {
  sessions:      'admin/sessions',
}

  devise_for :customers, controllers: {
  registrations:      'public/registrations',
  sessions:      'public/sessions',
}
# devise_for :customers, controllers: {
#   sessions:      'customers/sessions',
#   passwords:     'customers/passwords',
#   registrations: 'customers/registrations'
# }
scope module: :public do
  # get "/customers/sign_up" => "registrations#new", as: :new_customer_registration
  # post "/customers" => "registrations#create", as: :customer_registration
  # get "/customers/sign_in" => "sessions#new", as: :new_customer_session
  # post "/customers/sign_in" => "sessions#create", as: :customer_session
  # delete "/customers/sign_out" => "sessions#destroy", as: :destroy_customer_session
  root "homes#top"
  resources :homes, only:[:top]
  get "/about" => "homes#about"
  resources :items, only:[:index, :show]
  get "/customers/exit" => "customers#exit"
  patch "/customers/withdraw" => "customers#withdraw"
  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :customers, only:[:show, :edit, :update]
  resources :cart_items, only:[:index, :update, :create, :destroy]
  get "/orders/complete" => "orders#complete"
  post "/orders/confirm" => "orders#confirm"
  resources :orders, only:[:new, :index, :show, :create]
  resources :addresses, except:[:new, :show]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
namespace :admin do
  get "/" => "homes#top", as: :root
  resources :items
  resources :customers, only:[:index, :show, :edit, :update]
  resources :orders, only:[:show]
  put "/order_details/:id" => "order_details#update"
end

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
     belongs_to :customer
     belongs_to :item
 def subtotal
    item.with_tax_price * amount
 end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :is_deleted, inclusion: { in: [true, false] }
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/item.rb
class Item < ApplicationRecord
 attachment :image
 has_many :cart_items, dependent: :destroy
 has_many :order_details, dependent: :destroy
 has_many :orders, through: :order_details
def with_tax_price
    (price * 1.1).floor
end
end

app/models/order.rb
class Order < ApplicationRecord

enum payment_method: { credit_card: 0, transfer: 1 }
belongs_to :customer
has_many :order_details, dependent: :destroy
has_many :items, through: :order_details
has_one :current_order_order_detail, -> {where(main_flg: true)}, class_name: 'OrderDetail'
has_one :current_item, through: :current_order_order_detail, source: :order_detail
def subtotal
    item.order.with_tax_price * amount
end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
def with_tax_price
    (price * 1.1).floor
end
    
def subtotal
    item.order.with_tax_price * amount
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   layout 'admin'
  def top
   @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
     layout 'admin'
      before_action :authenticate_admin!
    def index
        @items = Item.all
    end

    def new
        @item = Item.new
    end

    def show
        @item = Item.find(params[:id])
    end


    def create
        item = Item.new(item_params)
        item.save
        redirect_to admin_item_path(item.id)
    end

    def edit
        @item = Item.find(params[:id])
    end

    def update
        item = Item.find(params[:id])
        item.update(item_params)
        redirect_to admin_item_path(item.id)
    end

    private

    def item_params
        params.require(:item).permit(:name, :introduction, :price, :image)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def current_cart_item
  #   if session[:cart_item_id]
  #     @cart_item = CartItem.find(session[:cart_item_id])
  #   else
  #     @cart_item = CartItem.create
  #     session[:cart_item_id] = @cart_item.id
  #   end
  # end
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:postal_code])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:telephone_number])
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LOGO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <meta name="viwport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-light navbar-light">
        <div class="container">
          <%= link_to'LOGO', root_path, class: 'nav-link text-dark' %>
          <!--<a class="navbar-brand p-3" href="/">Bookers</a>-->
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggle-icon"></span>
     </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
    <% if admin_signed_in? %>

    <li class="nav-item ">
      <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
     </i>


     <li class="nav-item ">
       <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
       </i>


      <li class="nav-item">
        <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark' %>
       </li>


      <li class="nav-item">
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
      </li>


    </li>

    <% else %>

    <li class="nav-item ">
      <%= link_to"About", about_path, class: 'nav-link text-dark' %>
      </i>

    <li class="nav-item">
      <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
    </li>

    <li class="naav-item">
      <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
      </li>
    <li class="nav-item"><%= link_to"ログイン", new_admin_session_path, class: 'nav-link text-dark' %>
    </li>

    </li>

    <% end %>
    </ul>
    </div>
    </div>
    </nav>
  </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <p class="text-center"></p>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LOGO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <meta name="viwport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-light navbar-light">
        <div class="container">
          <%= link_to'LOGO', root_path, class: 'nav-link text-dark' %>
          <!--<a class="navbar-brand p-3" href="/">Bookers</a>-->
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggle-icon"></span>
     </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
    <% if customer_signed_in? %>

     <li class="nav-item ">ようこそ！<%= current_customer.first_name %>さん</li>


    <li class="nav-item ">
      <%= link_to "マイページ", customer_path(current_customer.id), class: 'nav-link text-dark' %>
     </i>


     <li class="nav-item ">
       <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
       </i>


      <li class="nav-item">
        <%= link_to "カート", cart_items_path, class: 'nav-link text-dark' %>
       </li>


      <li class="nav-item">
      <%= link_to"ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
      </li>


    </li>

    <% else %>

    <li class="nav-item ">
      <%= link_to"About", about_path, class: 'nav-link text-dark' %>
      </i>

    <li class="nav-item">
      <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
    </li>

    <li class="naav-item">
      <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
      </li>
    <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
    </li>


    </li>

    <% end %>
    </ul>
    </div>
    </div>
    </nav>
  </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <p class="text-center"></p>
    </footer>
  </body>
</html>